apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    app: clickhouse-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clickhouse-db
  template:
    metadata:
      labels:
        app: clickhouse-db
    spec:
      containers:
        - name: clickhouse-server
          image: yandex/clickhouse-server:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/clickhouse-server/config.d
        - name: clickhouse-client
          image: yandex/clickhouse-client:latest
          command: ["tail", "-f", "/dev/null"]
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "clickhouse.fullname" . }}-config
            defaultMode: 0644
