apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  JWT_SECRET_KEY: YXNkZg==
  JWT_REFRESH_SECRET_KEY: YXNkZg==
  CLICKHOUSE_URL: bG9jYWxob3N0
  CLICKHOUSE_USER: Y2xpY2tob3VzZV9hZG1pbg==
  CLICKHOUSE_PASSWORD: MTIzNA==
  PROMETHEUS_URL: bG9jYWxob3N0
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlhudjN0ZUZLZzVAaGlnaHdheS1zZXJ2aWNlL2NoYWluZGVjay8=
  API_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
