# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgresql-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgresql
#   template:
#     metadata:
#       labels:
#         app: postgresql
#     spec:
#       containers:
#         - name: postgresql
#           image: postgres:latest
#           ports:
#             - containerPort: 5432
         


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app: postgresql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgresql:latest
          ports:
            - containerPort: 5432
           env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_DB
          