---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaindeck-api.fullname" . }}-service
spec:
  selector:
    app: chaindeck-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-service
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: native
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
