apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc }}
  JWT_REFRESH_SECRET_KEY: {{ .Values.secrets.jwtRefreshSecretKey | b64enc }}
  CLICKHOUSE_URL: {{ .Values.secrets.clickhouseUrl | b64enc }}
  CLICKHOUSE_USER: {{ .Values.secrets.clickhouseUser | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhousePassword | b64enc }}
  PROMETHEUS_URL: {{ .Values.secrets.prometheusUrl | b64enc }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}
  API_URL: {{ .Values.secrets.apiUrl | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | b64enc }}
